site_name: Python Maze Documentation
site_url: ""
use_directory_urls: false

nav:
    - Home: index.md
    - About: about.md
    - Setup: setup.md
    - DFS: algorithmDFS.md
    - Unittests: testing.md
    
theme:
    name: material
